<footer class="footer mt-auto py-3 bg-dark">
   <div class="container">
      <span class="text-muted">&copy; <?php echo  APP_NAME . ' by ' . APP_AUTHOR . ' ' . date('Y') ?></span>
      <div class="container">
         <a href="/legal/terms">Terms</a> | <a href="/legal/privacy">Privacy</a> | <a href="/legal/copyright">Copyright</a> | <a href="https://github.com/tnebes/iwtl-bootstrap-test" target="_blank" class="ml-auto">About</a>
      </div>
   </div>
</footer>