<?php declare(strict_types = 1);
$currentPage = (int) $currentPage;
$numberOfPages = (int) $numberOfPages;
?>

<div class="container text-center">
   <nav aria-label="...">
      <ul class="pagination justify-content-center">
         <li class="page-item <?php echo $currentPage < 2 ? 'disabled' : 'enabled'; ?>">
            <a class="page-link" href="<?php echo $link . $currentPage - 1; ?>" tabindex="-1">Previous</a>
         </li>
         <?php
         // extremely cursed.
         $initialisation = $currentPage - ceil(PAGINATION_BUTTONS / 2);
         $condition = $currentPage + ceil(PAGINATION_BUTTONS / 2);
         while ($initialisation < 1)
         {
            $initialisation++;
            $condition++;
         }
         if ($condition > $numberOfPages)
         {
            $condition = $numberOfPages;
         }
         if ($currentPage + ceil(PAGINATION_BUTTONS / 2) > $numberOfPages)
         {
            $initialisation -= $currentPage + ceil(PAGINATION_BUTTONS / 2) - $numberOfPages;
         }
          
         for ($i = $initialisation; $i <= $condition; $i++) :
         ?>
            <?php $onCurrentPage = $i == $currentPage ?>
            <li class="page-item <?php echo $onCurrentPage ? 'active' : ''; ?>">
               <a class="page-link" href="<?php echo $link . $i; ?>"><?php echo $i; ?> <span class="sr-only">(current)</span></a>
            </li>
         <?php endfor; ?>
         <li class="page-item <?php echo $currentPage >= $numberOfPages ? 'disabled' : 'enabled'; ?>">
            <a class="page-link" href="<?php echo $link . $currentPage + 1; ?>" tabindex="1">Next</a>
         </li>
      </ul>
   </nav>
</div>