<!-- bootstrap fancy entry with link to topic -->
<div class="card">
   <a href="<?php echo URL_ROOT . '/topics/topic/' . $subscription->topic?>">
      <?php echo $subscription->topicTitle; ?>
   </a>
   <p class="text-dark">
   Subscribed since: <?php echo $subscription->subscribedSince; ?>
   </p>
   <span class="badge rounded-pill bg-success"><a class="text-dark" href="<?php echo URL_ROOT . '/subscriptions/subscribe/' . $subscription->topic?>">Subscribe</a></span>
</div>