<div class="form-control ml-0">
   <span class="badge rounded-pill bg-info"><a class="text-dark" href="<?php echo URL_ROOT . 'users/user/' . $suggestion->user?>"><?php echo $suggestion->username?></a></span>
   <div class="col">
      <div class="row">
         <strong><?php echo $suggestion->shortDescription; ?></strong>
      </div>
      <div class="row">
         <?php echo $suggestion->longDescription; ?>
      </div>
      <div class="row">
         <small class="text-muted">
            <?php echo (new DateTime($suggestion->datePosted))->format('dS M Y'); ?>
         </small>
      </div>      
   </div>   
</div>