<div class="container border my-1 px-4 py-1" id="suggestion-<?php echo $suggestion->id;?>">
   <?php !is_null($suggestion->filePath) ? ImageGetter::getImage($suggestion->filePath, null, $suggestion->altText, 200, 200) : '';?>
   <a class="badge rounded-pill bg-info text-dark" href="<?php echo URL_ROOT . '/users/profile/' . $suggestion->user ?>"><?php echo $suggestion->username ?></a>
   <div class="col">
      <div class="row">
         <div class="col">
            <div class="row">
               <strong><?php echo $suggestion->shortDescription; ?></strong>
            </div>
            <div class="row">
               <?php echo $suggestion->longDescription; ?>
            </div>
            <div class="row">
               <small class="text-muted">
                  <?php echo (new DateTime($suggestion->datePosted))->format('dS M Y'); ?>
               </small>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col">
            <?php if (Helper::getInstance()->isAdmin() || (Helper::getInstance()->isLoggedIn() && $suggestion->user == $_SESSION['id'])) : ?>
               <div class="row">
                  <a href="<?php echo URL_ROOT . '/suggestions/edit/' . $suggestion->id; ?>" type="button" class="btn btn-success mt-1 btn-sm" role="button">Edit</a>
               </div>
               <div class="row">
                  <a href="<?php echo URL_ROOT . '/suggestions/delete/' . $suggestion->id; ?>" type="button" class="btn btn-danger mt-1 btn-sm" role="button">Delete</a>
               </div>
            <?php endif; ?>
         </div>
         <div class="col">
            <?php if (Helper::getInstance()->isLoggedIn()) : ?>
               <?php
               $userReview = (new UserSuggestionReview)->getReviewByUser((int) $_SESSION['id'], (int) $suggestion->id);
               ?>
               <div class="row">
                  <button id="suggestion-like-<?php echo $suggestion->id;?>" class="btn <?php echo $userReview == 1 ? 'btn-success' : 'btn-primary'; ?> mt-1 btn-sm " role="button">&#128077;</a>
               </div>
               <div class="row">
                  <button id="suggestion-dislike-<?php echo $suggestion->id;?>" class="btn <?php echo $userReview == -1 ? 'btn-danger' : 'btn-primary'; ?> mt-1 btn-sm" role="button">&#128078;</a>
               </div>
            <?php else : ?>
               <div class="row">
                  <a href="#" class="btn btn-outline-primary mt-1 disabled" disabled role="button">&#128077;</a>
               </div>
               <div class="row">
                  <a href="#" class="btn btn-outline-primary mt-1 disabled" disabled role="button">&#128078;</a>
               </div>
            <?php endif; ?>
         </div>
         <div class="col-3 my-auto">
            <div class="row justify-content-start align-items-center">
               <?php
               $reviewScore = (new UserSuggestionReview)->getReviewScore($suggestion->id);
               $liked = $reviewScore >= 0;
               if ($liked) : ?>
                  <i class="fas fa-3x fa-arrow-up" style="color: green"></i>
                  <h4>
                     <strong id="suggestion-likes-<?php echo $suggestion->id;?>" class="mx-3"><?php echo $reviewScore ?></strong>
                  </h4>
               <?php else : ?>
                  <i class="fas fa-3x fa-arrow-down" style="color: red"></i>
                  <h4>
                     <strong id="suggestion-likes-<?php echo $suggestion->id;?>" class="mx-3"><?php echo $reviewScore ?></strong>
                  </h4>
               <?php endif; ?>
            </div>
         </div>
      </div>
   </div>
</div>