<?php if (Helper::getInstance()->isAdmin()) : ?>
<div class="container border m-1 mx-auto pb-2" id="user-container">
   <div class="container p-0 pb-1 text-center">
      <a class="badge rounded-pill bg-info text-dark" href="<?php echo URL_ROOT . '/users/profile/' . $user->id?>"><?php echo $user->username?></a>
   </div>
   <div class="container p-0 m-0 text-danger text-center">
      <?php echo $user->banned != 0 ? '<strong>BANNED</strong>' : '' ?>
   </div>
   <div class="container" id="user-information">
      <div class="row">
         <div class="col">
            <div class="row">
               <strong>Date Registered:</strong>
            </div>
            <div class="row">
               <strong>Email:</strong>
            </div>
            <div class="row">
               <strong>Role:</strong>
            </div>
            <div class="row">
               <strong>Last Login:</strong>
            </div>
            <div class="row">
               <?php echo $user->banned != 0 ? '<strong>Date Banned:</strong>' : '' ?>
            </div>
         </div>
         <div class="col font-weight-light">
            <div class="row">
               <?php echo (new DateTime($user->registrationDate))->format('dS M Y'); ?>
            </div>
            <div class="row">
               <?php echo $user->email; ?>
            </div>
            <div class="row">
               <?php echo $user->role; ?>
            </div>
            <div class="row">
               <?php echo (new DateTime($user->lastLogin))->format('dS M Y'); ?>
            </div>
            <div class="row">
               <?php echo $user->banned ? (new DateTime($user->dateBanned))->format('dS M Y') : ''; ?>
            </div>
         </div>
      </div>
   </div>
   <div class="container p-0 m-0" id="actions">
      
   </div>
</div>
<?php else: ?>
   <div class="container border m-1 mx-auto pb-2" id="user-container">
   <div class="container p-0 pb-1 text-center">
      <a class="badge rounded-pill bg-info text-dark" href="<?php echo URL_ROOT . '/users/profile/' . $user->id?>"><?php echo $user->username?></a>
   </div>
   <div class="container p-0 m-0 text-danger text-center">
      <?php echo $user->banned != 0 ? '<strong>BANNED</strong>' : '' ?>
   </div>
   <div class="container" id="user-information">
      <div class="row">
         <div class="col">
            <div class="row">
               <strong>Date Registered:</strong>
            </div>
         </div>
         <div class="col font-weight-light">
            <div class="row">
               <?php echo (new DateTime($user->registrationDate))->format('dS M Y'); ?>
            </div>
         </div>
      </div>
   </div>
   <div class="container p-0 m-0" id="actions">
      actions go here.
   </div>
</div>
<?php endif; ?>