<div class="row w-75">
   <form method="POST" action="/topics/create">
   <!-- Title input -->
   <div class="form-outline mb-4">
      <input type="text" name="name" class="form-control" placeholder="<?php Helper::getInstance()->getRandomTopicTitle();?>"/>
   </div>

   <!-- Description input -->
   <div class="form-outline mb-4">
      <textarea class="form-control" name="description" rows="10" placeholder="Short description goes here."></textarea>
   </div>

   <!-- Submit button -->
   <button type="submit" id="submit" class="btn btn-primary btn-block mb-4">Send</button>
   </form>
</div>