<?php declare(strict_types = 1);

if (!isset($topics) && !is_array($topics) && !count($topics) > 0)
{
   // nice and shiny
   (new ControllerErrorPages)->internalError();
   return;
}
echo '<ul class="list-group">';
echo '<li class="list-group-item text-dark">';
foreach ($topics as $topic)
{
   ?>
   <div class="row">
      <div class="col-sm-6 col-md-4">
         <div class="thumbnail">
            <img src="...image..." alt="...img...">
            <div class="caption">
               <h3><?php echo $topic->name?></h3>
               <span class="label label-success"><?php echo getUserFromTopic($topic)->username ?></span>
               <p><?php echo $topic->description?></p>      
               <p class="center"><p><?php echo date('d-m-Y', strtotime($topic->datePosted))?></p></p>
               <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
            </div>
         </div>
      </div>
   </div>

   <?php
   echo '</li>';
}
echo '</ul>';

?>



