<?php declare(strict_types = 1);

if (!isset($topics) && !is_array($topics) && !count($topics) > 0)
{
   // Class member access on instantiation
   (new ControllerErrorPages)->internalError();
   return;
}
echo '<ul class="list-group">';
foreach ($topics as $topic)
{
   echo '<li class="list-group-item text-dark mx-auto my-2 w-50">';
   ?>
   <div class="thumbnail">
      <div class="caption">
         <img src="...image..." alt="...img...">
         <div class="form-control">
            <h1><a href="<?php echo getLinkToTopic($topic); ?>"><span class="badge bg-dark text-light"><?php echo $topic->name?></span></a></h1>
            <h6><a href="<?php echo getLinkToUser(getUserFromTopic($topic)); ?>"><span class="badge bg-info text-dark"><?php echo getUserFromTopic($topic)->username ?></span></a></h6>
            <p><?php echo $topic->description?></p>      
            <small class="text-muted" class="center">Date asked: <p><?php echo date('d-m-Y', strtotime($topic->datePosted))?></p></small>
         </div>

         <p>
            <!-- TODO: only if registered -->
            <?php if (isLoggedIn()) : ?>
            <a href="#" class="btn btn-primary mt-1" role="button">&#128077;</a>
            <a href="#" class="btn btn-primary mt-1" role="button">&#128078;</a>
            <a href="#" class="btn btn-primary mt-1" role="button">Suggest</a>
            <a href="#" class="btn btn-primary mt-1" role="button">Subscribe</a>
            <?php else: ?>
            <a href="#" class="btn btn-outline-primary mt-1 disabled" disabled role="button">&#128077;</a>
            <a href="#" class="btn btn-outline-primary mt-1 disabled" disabled role="button">&#128078;</a>
            <a href="#" class="btn btn-outline-primary mt-1 disabled" disabled role="button">Suggest</a>
            <a href="<?php echo URL_ROOT . '/users/login'?>"><p>Log in to rate, comment, and subscribe to this question.</p></a>

            <?php endif; ?>
         <p>
      </div>
      <!-- TODO: Top 5 rated comments go here -->
      <!-- foreach(getSuggestions($topic) as $suggestion) ... -->
   </div>

   <?php
   echo '</li>';
}
echo '</ul>';

?>



