<?php if (Helper::getInstance()->isAdmin()) : ?>
   <div class="card bg-dark">
      <div class="card-header">
         <h2 class="alert alert-primary">
            <?php
            echo $user->username ?>'s Profile
         </h2>
         <?php
         echo '<a class="btn btn-info" href=' . URL_ROOT . '/users/update/' . $user->id . '>Edit User</a>';
         echo '<a class="btn btn-danger" href=' . URL_ROOT . '/users/delete/' . $user->id . '>Delete User</a>';
         echo '<a class="btn btn-warning" href=' . URL_ROOT . '/users/ban/' . $user->id . '>Ban User</a>';
         ?>
      </div>
      <div class="card-body">
         <div class="row">
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Username</label>
               <p><?php echo $user->username ?></p>
            </div>
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Email</label>
               <p><?php echo $user->email ?></p>
            </div>
         </div>
         <div class="row">
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Registration Date</label>
               <p><?php echo $user->registrationDate ?></p>
            </div>
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Role</label>
               <p><?php echo Helper::getInstance()->roleToString($user->role); ?></p>
            </div>
         </div>
         <div class="row">
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Last Login</label>
               <p><?php echo $user->lastLogin ?></p>
            </div>
         </div>
         <div class="row">
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Banned</label>
               <p><?php echo Helper::getInstance()->bannedToCheckbox($user->banned, true) ?></p>
            </div>
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Date Banned</label>
               <p><?php echo $user->banned ? $user->dateBanned : ''; ?></p>
            </div>
         </div>
      </div>
   </div>
<?php else : ?>
   <div class="card bg-dark">
      <div class="card-header">
         <h2 class="alert alert-primary">
            <?php
            echo $user->username ?>'s Profile
         </h2>
      </div>
      <div class="card-body">
         <div class="row">
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Username</label>
               <p><?php echo $user->username ?></p>
            </div>
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Registration Date</label>
               <p><?php echo $user->registrationDate ?></p>
            </div>
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Role</label>
               <p><?php echo $user->role ?></p>
            </div>
         </div>
         <div class="row">
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Banned</label>
               <p><?php echo $user->banned ?></p>
            </div>
            <div class="col-md-6">
               <label class="badge bg-info text-dark">Date Banned</label>
               <p><?php echo $user->dateBanned ?></p>
            </div>
         </div>
      </div>
   </div>
<?php endif; ?>