<main class="form-signin">
   <form class="from-inline" method="POST" action="/users/register">
      <img class="mb-4" src="/img/logo2.png" width="150">
      <h1 class="h2 mb-3 fw-normal">Register</h1>
      <label for="username">Username</label>
      <?php if (!empty($usernameError)) : ?>
         <span class="text-warning" role="alert"><?php echo $usernameError ?></span>
      <?php endif; ?>
      <input type="text" class="form-control" id="username" name="username" placeholder="username">
      <div class="form-floating">
         <label for="email">Email address</label>
         <?php if (!empty($emailError)) : ?>
            <span class="text-warning"><?php echo $usernameError ?></span>
         <?php endif; ?>
         <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
      </div>
      <div class="form-floating">
         <label for="password">Password</label>
         <?php if (!empty($passwordError)) : ?>
            <span class="text-warning"><?php echo $usernameError ?></span>
         <?php endif; ?>
         <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      </div>
      <div class="form-floating">
         <label for="password">Confirm Password</label>
         <?php if (!empty($confirmPasswordError)) : ?>
            <span class="text-warning"><?php echo $usernameError ?></span>
         <?php endif; ?>
         <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" placeholder="Confirm Password">
      </div>
      <button class="w-75 btn btn-lg btn-info mb-5" type="submit" id="submit" value="submit">Register</button>
   </form>
</main>