<?php

declare(strict_types=1);
$numberOfSuggestions = -1;
echo '<ul class="list-group">';
include APP_ROOT . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'topic.phtml';
echo '</ul>';

?>

<div class="container mt-5">
   <form method="POST" action="/suggestions/create/<?php echo $topic->id ?>" enctype="multipart/form-data">
      <!-- Title input -->
      <div class="form-outline mx-auto mb-4">
          <label for="title"><h1>Title of your answer</h1></label>
         <input type="text" id="title" name="title" class="form-control" value="<?php echo $suggestionTitle ?>" placeholder="Title of your answer." />
         <?php if (!empty($suggestionTitleError)) : ?>
            <span class="text-warning" role="alert"><?php echo $suggestionTitleError ?></span>
         <?php endif; ?>
      </div>

      <!-- Description input -->
      <div class="form-outline mb-4">
         <label for="longDescription"><h2>Description of your question (optional)</h2></label>
         <textarea class="form-control" id="longDescription" name="longDescription" rows="10" placeholder="Long answer goes here."><?php echo $suggestionLongDescription ?></textarea>
         <?php if (!empty($suggestionLongDescriptionError)) : ?>
            <span class="text-warning" role="alert"><?php echo $suggestionLongDescriptionError ?></span>
         <?php endif; ?>

      </div>
      <div class="form-outline mb-4">
         <label for="shortDescription"><h2>tl;dr (too long didn't read)</h2></label>
         <textarea class="form-control" id="shortDescription" name="shortDescription" rows="5" placeholder="Short answer goes here."><?php echo $suggestionShortDescription ?></textarea>
         <?php if (!empty($suggestionShortDescriptionError)) : ?>
            <span class="text-warning" role="alert"><?php echo $suggestionShortDescriptionError ?></span>
         <?php endif; ?>
      </div>

      <div class="form-outline mb-4">
         <div class="container p-0 m-0">
            <label for="image"><h2>Optional image</h2></label><br />
            <input type="hidden" name="MAX_FILE_SIZE" value="<?php echo FILE_UPLOAD_SIZE?>">
            <input class="p-1" type="file" name="image" id="image">
            <?php if (!empty($suggestionImageError)) : ?>
               <span class="text-warning" role="alert"><?php echo $suggestionImageError ?></span>
            <?php endif; ?>
         </div>
      </div>

      <!-- Submit button -->
      <button type="submit" id="submit" name="submit" class="btn btn-primary btn-block mb-4" value="true">Suggest</button>
   </form>
</div>